"Integrate the two repeats for each cluster using Harmony. Use the RDS files generated by running separate_clusters.R

Usage: integrate_clusters.R --file_sc_obj=<file> --file_functions=<file>

Options:
  -h --help			Show this screen.
  --file_sc_obj=<file>		The rds file after clustering
  --file_functions=<file> The .R file containing all functions
" -> doc

# Load libraries
suppressMessages(library(Seurat))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(cowplot))
suppressMessages(library(docopt))
suppressMessages(library(harmony))

# --- Read all the arguments passed
arguments <- docopt(doc, quoted_args=TRUE)

# --- Parameters: Read in the output of the sc_multi_sample pipline
file_sc_obj <- arguments$file_sc_obj
file_functions <- arguments$file_functions

message("file_sc_obj: ", file_sc_obj)
message("file_functions: ", file_functions)

# load all functions defined in the r-script
source(file_functions)

# read file
sc_obj <- readRDS(file_sc_obj)

# ***** integrate individual clusters for the two repeats
# first define functions to run seurat integration - not used here.
seurat_integration <- function(sc_obj=sc_obj){
  if(ncol(sc_obj) > 1000){
          npcs <- 20
          nhvg <- 4000
          } else {
          npcs = 10
          nhvg <- 1000
          }
  sc_obj_list <- SplitObject(sc_obj, split.by = "rep")

  sc_obj_int <- perform_standard_integration(sc_list=sc_obj_list, reference=NULL, anchor.features=nhvg, reduction="cca", dims=1:npcs, sample.tree=NULL, covars=NULL) %>%
    RunPCA(npcs=npcs) %>%
    RunUMAP(dims=1:npcs, seed.use=111)

  return(sc_obj_int)
}

# Define function to run Harmony integration. Note, it calls another function stored in functions.R file
harmony_integration <- function(sc_obj=sc_obj){
  if(ncol(sc_obj) > 1000){
          npcs <- 20
          nhvg <- 4000
          } else {
          npcs = 10
          nhvg <- 1000
          }

	sc_obj_int <- perform_harmony_integration(sc=sc_obj, npcs=npcs, nclust=2, group.by.vars="rep") %>%
    RunUMAP(dims=1:npcs, seed.use=111, reduction="harmony")

  return(sc_obj_int)
}

# Do the integration

#sc_obj_int <- seurat_integration(sc_obj=sc_obj) #The integration with Seurat function not yielding good results
sc_obj_int <- harmony_integration(sc_obj=sc_obj) #This is the one used.

file_sc_obj_int <- gsub(file_sc_obj, pattern=".rds", replacement="_int.rds")
saveRDS(object=sc_obj_int, file=file_sc_obj_int)
